### ISSUE TITLE
Can't find file VOC2012/ImageSets/Segmentation/list/train_aug.txt

### ISSUE THREAD

**Issue by zhangyuygss** [coallaoh/GuidedLabelling#1]
Seems the code tried to find file _VOC2012/ImageSets/Segmentation/list/train_aug.txt_. But I can't find this file in my VOC2012 trainval or test set. Should I download it elsewhere?

`Traceback (most recent call last):
  File "./script.py", line 60, in <module>
    seed_train(control, conf)
  File "src/seed/train.py", line 152, in main
    solver = load_solver(control, control_token, conf)
  File "src/seed/train.py", line 141, in load_solver
    solver = caffe.SGDSolver(solverproto)
  File "lib/caffetools/datalayers.py", line 22, in setup
    self.batch_loader = BatchLoader_PASCAL(params)
  File "lib/caffetools/datalayers.py", line 57, in __init__
    self.pascal_split)
  File "lib/pascaltools/io.py", line 32, in get_pascal_indexlist
    pascal_tmp_list = [line.rstrip('\n') for line in open(pascal_list_file)]
IOError: [Errno 2] No such file or directory: '/disk2/zhangyu/data/VOCdevkit/VOC2012/ImageSets/Segmentation/list/train_aug.txt'`

**Comment by coallaoh** [comment]
Hi, thanks for finding this out.
`train_aug.txt` is basically from the following link 
http://home.bharathh.info/pubs/codes/SBD/download.html
It's a standard training set for many Pascal semantic segmentors.

I've updated the repository so that you only need to run the updated version of `download.sh` -- it should download `train_aug.txt` and put it in the correct location (you should specify the `PASCALROOT` in the script though).

Let me know if there are further problems.
